import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'analytics_events.dart';

/// Analytics ラッパー — firebase_analytics 無効時は完全 no-op。
///
/// firebase_analytics パッケージが iOS で Firebase Installations の
/// API Key 検証を引き起こし crash するため、Phase 0 では no-op 実装を使用。
/// Firebase プロジェクト設定が本番環境で確認できたら firebase_analytics を
/// re-enable して FirebaseAnalytics.instance を使う。
class AnalyticsService {
  // ignore: unused_field
  final bool _enabled = false;

  /// Safe wrapper for logging events — currently no-op.
  Future<void> _logEvent(String name, {Map<String, Object>? parameters}) async {
    // No-op: firebase_analytics disabled for Phase 0 local testing.
    // When re-enabled, replace with FirebaseAnalytics.instance.logEvent(...).
  }

  // ─── Chat ────────────────────────────────────────────────

  Future<void> logChatMessageSent({
    required String domain,
    required String tier,
    required String locale,
  }) async {
    await _logEvent(
      AnalyticsEvents.chatMessageSent,
      parameters: {'domain': domain, 'tier': tier, 'locale': locale},
    );
  }

  Future<void> logChatFeedback({
    required String domain,
    required String rating,
    required String sessionId,
  }) async {
    await _logEvent(
      AnalyticsEvents.chatFeedback,
      parameters: {'domain': domain, 'rating': rating, 'session_id': sessionId},
    );
  }

  // ─── Navigator ───────────────────────────────────────────

  Future<void> logGuideViewed({
    required String domain,
    required String slug,
  }) async {
    await _logEvent(
      AnalyticsEvents.guideViewed,
      parameters: {'domain': domain, 'slug': slug},
    );
  }

  // ─── Subscription ────────────────────────────────────────

  Future<void> logSubscriptionStarted({
    required String tier,
    required String platform,
    required double price,
  }) async {
    await _logEvent(
      AnalyticsEvents.subscriptionStarted,
      parameters: {'tier': tier, 'platform': platform, 'price': price},
    );
  }

  // ─── Tracker ─────────────────────────────────────────────

  Future<void> logTrackerItemCompleted({bool autoGenerated = true}) async {
    await _logEvent(
      AnalyticsEvents.trackerItemCompleted,
      parameters: {'domain': 'tracker', 'auto_generated': autoGenerated},
    );
  }

  // ─── Onboarding ──────────────────────────────────────────

  Future<void> logOnboardingCompleted({
    required String nationality,
    required String residenceStatus,
  }) async {
    await _logEvent(
      AnalyticsEvents.onboardingCompleted,
      parameters: {
        'nationality': nationality,
        'residence_status': residenceStatus,
      },
    );
  }

  // ─── Emergency ───────────────────────────────────────────

  Future<void> logEmergencyAccessed({required bool authenticated}) async {
    await _logEvent(
      AnalyticsEvents.emergencyAccessed,
      parameters: {'authenticated': authenticated},
    );
  }

  // ─── Usage Limit ─────────────────────────────────────────

  Future<void> logUsageLimitReached({
    required String tier,
    required int used,
    required int limit,
  }) async {
    await _logEvent(
      AnalyticsEvents.usageLimitReached,
      parameters: {'tier': tier, 'used': used, 'limit': limit},
    );
  }

  // ─── Upgrade CTA ─────────────────────────────────────────

  Future<void> logUpgradeCTAShown({
    required String tier,
    required String source,
  }) async {
    await _logEvent(
      AnalyticsEvents.upgradeCTAShown,
      parameters: {'tier': tier, 'source': source},
    );
  }

  Future<void> logUpgradeCTATapped({
    required String tier,
    required String source,
  }) async {
    await _logEvent(
      AnalyticsEvents.upgradeCTATapped,
      parameters: {'tier': tier, 'source': source},
    );
  }
}

/// Riverpod provider for [AnalyticsService].
final analyticsServiceProvider = Provider<AnalyticsService>((ref) {
  return AnalyticsService();
});
