import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'analytics_events.dart';

/// Firebase Analytics ラッパー — Firebase 未初期化時は no-op。
///
/// 開発環境では Firebase が mock モード (FIREBASE_CREDENTIALS 未設定) のため、
/// 全メソッドを try-catch で囲み、例外時は静かに無視する。
class AnalyticsService {
  AnalyticsService() {
    try {
      _analytics = FirebaseAnalytics.instance;
      _enabled = true;
    } catch (_) {
      _enabled = false;
    }
  }

  late final FirebaseAnalytics _analytics;
  bool _enabled = false;

  /// Safe wrapper for logging events — no-op on failure.
  Future<void> _logEvent(String name, {Map<String, Object>? parameters}) async {
    if (!_enabled) return;
    try {
      await _analytics.logEvent(name: name, parameters: parameters);
    } catch (_) {
      // Graceful no-op: Firebase not available or not initialized.
    }
  }

  // ─── Chat ────────────────────────────────────────────────

  /// Chat 送信成功時。
  Future<void> logChatMessageSent({
    required String domain,
    required String tier,
    required String locale,
  }) async {
    await _logEvent(
      AnalyticsEvents.chatMessageSent,
      parameters: {'domain': domain, 'tier': tier, 'locale': locale},
    );
  }

  /// フィードバックボタン押下時。
  Future<void> logChatFeedback({
    required String domain,
    required String rating,
    required String sessionId,
  }) async {
    await _logEvent(
      AnalyticsEvents.chatFeedback,
      parameters: {'domain': domain, 'rating': rating, 'session_id': sessionId},
    );
  }

  // ─── Navigator ───────────────────────────────────────────

  /// ガイド詳細画面表示時。
  Future<void> logGuideViewed({
    required String domain,
    required String slug,
  }) async {
    await _logEvent(
      AnalyticsEvents.guideViewed,
      parameters: {'domain': domain, 'slug': slug},
    );
  }

  // ─── Subscription ────────────────────────────────────────

  /// サブスク購入成功時。
  Future<void> logSubscriptionStarted({
    required String tier,
    required String platform,
    required double price,
  }) async {
    await _logEvent(
      AnalyticsEvents.subscriptionStarted,
      parameters: {'tier': tier, 'platform': platform, 'price': price},
    );
  }

  // ─── Tracker ─────────────────────────────────────────────

  /// Tracker ステータスを completed に変更時。
  Future<void> logTrackerItemCompleted({bool autoGenerated = true}) async {
    await _logEvent(
      AnalyticsEvents.trackerItemCompleted,
      parameters: {'domain': 'tracker', 'auto_generated': autoGenerated},
    );
  }

  // ─── Onboarding ──────────────────────────────────────────

  /// オンボーディング完了時。
  Future<void> logOnboardingCompleted({
    required String nationality,
    required String residenceStatus,
  }) async {
    await _logEvent(
      AnalyticsEvents.onboardingCompleted,
      parameters: {
        'nationality': nationality,
        'residence_status': residenceStatus,
      },
    );
  }

  // ─── Emergency ───────────────────────────────────────────

  /// Emergency 画面表示時。
  Future<void> logEmergencyAccessed({required bool authenticated}) async {
    await _logEvent(
      AnalyticsEvents.emergencyAccessed,
      parameters: {'authenticated': authenticated},
    );
  }

  // ─── Usage Limit ─────────────────────────────────────────

  /// Chat で 429 エラー受信時。
  Future<void> logUsageLimitReached({
    required String tier,
    required int used,
    required int limit,
  }) async {
    await _logEvent(
      AnalyticsEvents.usageLimitReached,
      parameters: {'tier': tier, 'used': used, 'limit': limit},
    );
  }

  // ─── Upgrade CTA ─────────────────────────────────────────

  /// CTA バナー表示時。
  Future<void> logUpgradeCTAShown({
    required String tier,
    required String source,
  }) async {
    await _logEvent(
      AnalyticsEvents.upgradeCTAShown,
      parameters: {'tier': tier, 'source': source},
    );
  }

  /// CTA ボタンタップ時。
  Future<void> logUpgradeCTATapped({
    required String tier,
    required String source,
  }) async {
    await _logEvent(
      AnalyticsEvents.upgradeCTATapped,
      parameters: {'tier': tier, 'source': source},
    );
  }
}

/// Riverpod provider for [AnalyticsService].
final analyticsServiceProvider = Provider<AnalyticsService>((ref) {
  return AnalyticsService();
});
